name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: |
          bun lint
          bun format:check
        env:
          SKIP_ENV_VALIDATION: true

      - name: Run typecheck
        run: bun ts:check

      - name: Run tests
        run: bun test
